# To copy & run our main React build-
FROM node:18
WORKDIR /usr/app

COPY ./package*.json /usr/app/.
COPY ./public /usr/app/.
COPY ./src /usr/app/.

RUN npm install

EXPOSE 3000

CMD ["npm", "run", "serve"]
