/**
 *
 * DO NOT EDIT THIS FILE!
 *
 * This file is merely a loader for the infinitymint.config.js and you should put inside of the hardhat key what ever you would
 * put inside of here.
 */

// Dem aliases doe.
import 'module-alias/register';
// Import our hardhat plugins
import '@nomicfoundation/hardhat-toolbox';
import '@nomiclabs/hardhat-ethers';
import 'hardhat-deploy';
import 'hardhat-change-network'; // Allows hre.changeNetwork to occur
import {
  prepareConfig,
  loadInfinityMint,
  logDirect,
} from 'infinitymint/dist/app/helpers';
import { createDefaultFactory } from 'infinitymint/dist/app/pipes';

// Create default pipe
createDefaultFactory();

// Require dotenv
require('dotenv').config({
  override: false, // Will not override already established environment variables
});

// Load infinitymint and create default files
loadInfinityMint(false, true);

// Return the infinitymint config file
const config = prepareConfig();

export default config.hardhat; // Export the infinity mint configuration file
