/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/aspect-ratio'),
    require('daisyui'),
  ],
  daisyui: {
    themes: [
      {
        Ox0z_light : {
          'fontFamily': "'Lora', sans-serif",
          'primary': '#facc15',
          'secondary': '#ec4899',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🟨',
        },
        Ox0z_dark : {
          'fontFamily': 'Lora, sans-serif',
          'primary': '#facc15',
          'secondary': '#ec4899',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🟨'
        },
        emerald_city_light: {
          'fontFamily': 'Orbitron, sans-serif',
          'primary': '#30bb78',
          'secondary': '#FF46B1',
          'accent': '#dbffe5',
          'neutral': '#98e2b3',
          'base-100': '#1F212E',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#ff8700',
          'error': '#e11d48',
          'emoji-modifier': '🟩'
        },
        emerald_city_dark: {
          'fontFamily': 'Orbitron, sans-serif',
          'primary': '#30bb78',
          'secondary': '#FF46B1',
          'accent': '#dbffe5',
          'neutral': '#98e2b3',
          'base-100': '#0A0B14',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#ff8700',
          'error': '#e11d48',
          'emoji-modifier': '🟩'
        },
        'OxWizardof0z_light': {
          'fontFamily': 'Inconsolata, monospace',
          'primary': '#8158FC',
          'secondary': '#1FAB89',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🧙‍♂️'
        },
        'OxWizardof0z_dark': {
          'fontFamily': 'Inconsolata, monospace',
          'primary': '#8158FC',
          'secondary': '#1FAB89',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🧙‍♂️'
        },
        'OxDorothy_light': {
          'fontFamily': 'Bebas Neue, sans-serif',
          'primary': '#DA4453',
          'secondary': '#D2E1FF',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '👠'
        },
        'OxDorothy_dark': {
          'fontFamily': 'Bebas Neue, sans-serif',
          'primary': '#DA4453',
          'secondary': '#D2E1FF',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '👠'
        },
        'OxToto_light': {
          'fontFamily': 'Pacifico, cursive',
          'primary': '#8158FC',
          'secondary': '#FF46B1',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🐶'
        },
        'OxToto_dark': {
          'fontFamily': 'Pacifico, cursive',
          'primary': '#8158FC',
          'secondary': '#FF46B1',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🐶'
        },
        'OxScarecrow_light': {
          'fontFamily': 'Press Start 2P, cursive',
          'primary': '#facc15',
          'secondary': '#ec4899',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '😱'
        },
        'OxScarecrow_dark': {
          'fontFamily': 'Press Start 2P, cursive',
          'primary': '#facc15',
          'secondary': '#ec4899',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '😱'
        },
        'OxTinMan_light': {
          'fontFamily': 'Roboto Mono, monospace',
          'primary': '#3D3D3D',
          'secondary': '#8C8C8C',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🤖'
        },
        'OxTinMan_dark': {
          'fontFamily': '"Roboto Mono"',
          'primary': '#3D3D3D',
          'secondary': '#8C8C8C',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🤖'
        },
        'OxLionheart_light': {
          'fontFamily': '"Lobster"',
          'primary': '#FC8A4C',
          'secondary': '#FFC107',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🦁'
        },
        'OxLionheart_dark': {
          'fontFamily': 'Lobster',
          'primary': '#FC8A4C',
          'secondary': '#FFC107',
          'accent': '#d946ef',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🦁'
        },
        'OxGoodWitch_light': {
          'fontFamily': 'Dancing Script',
          'primary': '#FF79E1',
          'secondary': '#C56CF0',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🧙‍♀️'
        },
        'OxGoodWitch_dark': {
          'fontFamily': 'Dancing Script',
          'primary': '#FF79E1',
          'secondary': '#C56CF0',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🧙‍♀️'
        },
        'OxBadWitch_light': {
          'fontFamily': 'Amatic SC',
          'primary': '#4B4B4B',
          'secondary': '#1E1E1E',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🧙‍♀️'
        },
        'OxBadWitch_dark': {
          'fontFamily': 'Amatic SC',
          'primary': '#4B4B4B',
          'secondary': '#1E1E1E',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🧙‍♀️'
        },
        'OxMunchkin_light': {
          'fontFamily': 'Luckiest Guy',
          'primary': '#F8961E',
          'secondary': '#90BE6D',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#fde047',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🌈'
          },
          'OxMunchkin_dark': {
          'fontFamily': 'Luckiest Guy',
          'primary': '#F8961E',
          'secondary': '#90BE6D',
          'accent': '#dbffe5',
          'neutral': '#eab308',
          'base-100': '#1c1917',
          'info': '#A5DEF3',
          'success': '#059669',
          'warning': '#fecdd3',
          'error': '#e11d48',
          'emoji-modifier': '🌈'
          }
      },
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
    ],
  },
  theme: {
    extend: {
      fontFamily: {
        apocalypse: ['Apocalypse Grunge'],
        thenextfont: ['TheNextFont', 'sans-serif'],
        lobster: ['Lobster'],
        dancing: ['Dancing Script'],
        amatic: ['Amatic SC'],
        luckiest: ['Luckiest Guy'],
        roboto: ['Roboto Mono', 'sans-serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        lora: ['Lora', 'serif'],
      },

      fontSize: {
        '10xl': '5rem',
        '11xl': '5.5rem',
        '12xl': '6rem',
        '13xl': '6.5rem',
        '14xl': '7rem',
        '15xl': '7.5rem',
        '16xl': '8rem',
        giant: '11rem',
      },
    },
  },
};
