const config = {
  providerUrl: 'https://mainnet.infura.io/v3/669e602e2d6f4709a305b9e619d6020c',
  ipfsProviderURL: 'https://dweb.link/api/v0',
  ipfsWebProvider: 'https://dweb.link/ipfs/',
  chatGPTApiKey: '',
  chatGPTModel: '',
  chatGPTMaxTokens: 100,
  chatGPTTemperature: 0.7,
  chatGPTTopP: 1,
  useLocalApi: true,
  localApiEndpoint: 'http://localhost:9090/',
  apiEndpoint: 'https://web-api.infinitymint.app/',
  /**
   * routes for the api system, don't change these
   */
  routes: {
    gpt3: 'gpt3',
    search: 'search',
    nft: 'nft',
    ipfs: 'ipfs',
    ipns: 'ipns',
    wallet: 'wallet',
  },
  defaultAvatar:
    'https://cdn.pixabay.com/photo/2016/08/08/09/17/avatar-1577909_640.png',
  themes: [
    'light',
    'dark',
    'cupcake',
    'bumblebee',
    'emerald',
    'corporate',
    'synthwave',
    'retro',
    'cyberpunk',
    'valentine',
    'halloween',
    'garden',
    'forest',
    'aqua',
    'lofi',
    'pastel',
    'fantasy',
    'wireframe',
    'black',
    'luxury',
    'dracula',
    'cmyk',
    'autumn',
    'business',
    'acid',
    'lemonade',
    'night',
    'coffee',
    'winter',
  ],
  resolvers: [
    ['.vision', ''],
    ['.im', ''],
    ['.infinitymint', '.eth'],
    ['.ethereum', '.eth'],
  ],
};

export default config;
